import argon2 from 'argon2';import {randomBytes} from 'node:crypto';import {z} from 'zod';import {q,tx,outbox} from './db.mjs';import {hash,secret,fail,encrypt,decrypt,base32,verifyTotp,blind} from './security.mjs';
const cookieOpts=()=>({httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/'});
export const publicUser=u=>u?{id:u.id,email:u.email,name:u.name,role:u.role,emailVerified:u.email_verified,totpEnabled:u.totp_enabled}:null;
export async function loadSession(req){req.clientIp=req.headers['x-client-ip']||req.socket.remoteAddress;const token=req.cookies?.nexo_session;if(!token)return;const {rows}=await q("SELECT s.*,u.email,u.name,u.role,u.status,u.email_verified,u.totp_enabled FROM sessions s JOIN users u ON s.user_id=u.id WHERE s.id_hash=$1 AND s.expires_at>now()",[hash(token)]);const s=rows[0];if(s&&s.status==='ACTIVE'){req.session=s;req.user={...s,id:s.user_id};}}
export function requireUser(req,roles,allowPartial=false){if(!req.user)fail(401,'Iniciá sesión para continuar.');if(!allowPartial&&(req.session.stage!=='FULL'||!req.user.email_verified||(req.user.role==='CREATOR'&&!req.user.totp_enabled)))fail(403,'Completá la verificación de email y autenticación.');if(roles&&!roles.includes(req.user.role))fail(403,'No tenés permiso para esta acción.');return req.user}
async function newSession(c,req,res,u,stage){const token=secret(),device=req.cookies?.nexo_device||secret();if(req.cookies?.nexo_session)await c.query('DELETE FROM sessions WHERE id_hash=$1',[hash(req.cookies.nexo_session)]);await c.query('INSERT INTO sessions(id_hash,user_id,stage,device_hash,ip,user_agent,expires_at) VALUES($1,$2,$3,$4,$5,$6,now()+$7::interval)',[hash(token),u.id,stage,hash(device),req.clientIp,req.headers['user-agent']||'',stage==='FULL'?'12 hours':'10 minutes']);res.cookie('nexo_session',token,{...cookieOpts(),maxAge:stage==='FULL'?43200000:600000});res.cookie('nexo_device',device,{...cookieOpts(),maxAge:31536000000});if(stage==='FULL')await completeLogin(c,req,u,hash(device));}
async function completeLogin(c,req,u,device){const inserted=await c.query('INSERT INTO trusted_devices(user_id,device_hash) VALUES($1,$2) ON CONFLICT DO NOTHING RETURNING user_id',[u.id,device]);await c.query("INSERT INTO login_events(user_id,ip,result,device_hash,user_agent) VALUES($1,$2,'SUCCESS',$3,$4)",[u.id,req.clientIp,device,req.headers['user-agent']||'']);if(inserted.rowCount&&u.role==='CREATOR')await outbox(c,'new-device:'+u.id+':'+device,'email',{to:u.email,subject:'Nuevo inicio de sesión en tu cuenta CREADOR',text:`Se inició sesión desde un dispositivo nuevo. IP: ${req.clientIp}. Si no fuiste vos, cambiá tu contraseña y revocá las sesiones.`});}
async function verification(c,u){const t=secret();await c.query("INSERT INTO verification_tokens(token_hash,user_id,purpose,expires_at) VALUES($1,$2,'EMAIL',now()+interval '1 day')",[hash(t),u.id]);await outbox(c,'verify:'+hash(t),'email',{to:u.email,subject:'Verificá tu email en Nexo',text:`Confirmá tu email: ${process.env.APP_ORIGIN}/verificar-email?token=${t}`})}
export function authRoutes(route){
 route('get','/auth/me',async req=>({user:req.session?.stage==='FULL'?publicUser(req.user):null,stage:req.session?.stage}));
 route('post','/auth/register',async(req)=>{const d=z.object({email:z.string().email().max(254),password:z.string().min(12).max(200),name:z.string().min(2).max(80),acceptedTerms:z.literal(true)}).parse(req.body);const email=d.email.trim().toLowerCase();await tx(async c=>{const s=(await c.query("SELECT value FROM settings WHERE key='legalReady'")).rows[0];if(!s?.value)fail(503,'Los registros aún no están habilitados.');if((await c.query("SELECT 1 FROM blocklist WHERE (kind='EMAIL' AND value_hash=$1) OR (kind='IP' AND value_hash=$2)",[blind(email),blind(req.clientIp)])).rowCount)fail(403,'No se puede registrar esta cuenta.');if((await c.query('SELECT 1 FROM users WHERE email=$1',[email])).rowCount)fail(409,'No se pudo crear la cuenta. Si ya existe, recuperá tu contraseña.');const u=(await c.query('INSERT INTO users(email,password_hash,name) VALUES($1,$2,$3) RETURNING *',[email,await argon2.hash(d.password,{type:argon2.argon2id}),d.name])).rows[0];await c.query('INSERT INTO communication_preferences(user_id) VALUES($1)',[u.id]);await c.query("INSERT INTO legal_acceptances(user_id,version,kind) VALUES($1,'2026-09-21','TERMS')",[u.id]);await verification(c,u)});return {message:'Revisá tu email para verificar la cuenta.'}});
 route('post','/auth/login',async(req,res)=>{const d=z.object({email:z.string().email().max(254),password:z.string().max(200)}).parse(req.body);const u=(await q('SELECT * FROM users WHERE email=$1',[d.email.trim().toLowerCase()])).rows[0];if(!u||!await argon2.verify(u.password_hash,d.password)){await q("INSERT INTO login_events(user_id,ip,result) VALUES($1,$2,'FAILED')",[u?.id||null,req.clientIp]);fail(401,'Email o contraseña incorrectos.')}if(u.status!=='ACTIVE')fail(403,'Esta cuenta no está activa.');if(!u.email_verified){await tx(c=>verification(c,u));fail(403,'Verificá tu email. Te enviamos un enlace para confirmarlo.')}const stage=u.totp_enabled?'TOTP':u.role==='CREATOR'?'TOTP_SETUP':'FULL';await tx(c=>newSession(c,req,res,u,stage));return {user:publicUser(u),stage:stage==='TOTP'?'totp':stage==='TOTP_SETUP'?'totp_setup':null}});
 route('post','/auth/logout',async(req,res)=>{if(req.cookies?.nexo_session)await q('DELETE FROM sessions WHERE id_hash=$1',[hash(req.cookies.nexo_session)]);res.clearCookie('nexo_session',cookieOpts());return {ok:true}});
 route('post','/auth/verify-email',async req=>{const token=z.string().min(20).max(200).parse(req.body.token);await tx(async c=>{const t=(await c.query("SELECT * FROM verification_tokens WHERE token_hash=$1 AND purpose='EMAIL' AND used_at IS NULL AND expires_at>now() FOR UPDATE",[hash(token)])).rows[0];if(!t)fail(400,'El enlace expiró o ya fue utilizado.');await c.query('UPDATE users SET email_verified=true WHERE id=$1',[t.user_id]);await c.query('UPDATE verification_tokens SET used_at=now() WHERE token_hash=$1',[hash(token)])});return {ok:true}});
 route('post','/auth/forgot-password',async req=>{const email=z.string().email().parse(req.body.email);await tx(async c=>{const u=(await c.query('SELECT id,email FROM users WHERE email=$1',[email.toLowerCase()])).rows[0];if(!u)return;const token=secret();await c.query("INSERT INTO verification_tokens(token_hash,user_id,purpose,expires_at) VALUES($1,$2,'PASSWORD',now()+interval '30 minutes')",[hash(token),u.id]);await outbox(c,'reset:'+hash(token),'email',{to:u.email,subject:'Recuperá tu acceso a Nexo',text:`Restablecé tu contraseña: ${process.env.APP_ORIGIN}/recuperar?token=${token}. El segundo factor sigue siendo obligatorio.`})});return {ok:true}});
 route('post','/auth/reset-password',async req=>{const d=z.object({token:z.string().min(20),password:z.string().min(12).max(200)}).parse(req.body);await tx(async c=>{const t=(await c.query("SELECT * FROM verification_tokens WHERE token_hash=$1 AND purpose='PASSWORD' AND used_at IS NULL AND expires_at>now() FOR UPDATE",[hash(d.token)])).rows[0];if(!t)fail(400,'Enlace inválido o vencido.');await c.query('UPDATE users SET password_hash=$1 WHERE id=$2',[await argon2.hash(d.password,{type:argon2.argon2id}),t.user_id]);await c.query('DELETE FROM sessions WHERE user_id=$1',[t.user_id]);await c.query('UPDATE verification_tokens SET used_at=now() WHERE token_hash=$1',[hash(d.token)])});return {ok:true}});
 route('post','/auth/totp/setup',async req=>{requireUser(req,null,true);if(req.session.stage!=='TOTP_SETUP')fail(403,'La configuración TOTP no está disponible en esta sesión.');return tx(async c=>{const u=(await c.query('SELECT * FROM users WHERE id=$1 FOR UPDATE',[req.user.id])).rows[0];if(u.totp_enabled)fail(409,'El segundo factor ya está activo.');const s=u.totp_secret?decrypt(u.totp_secret):base32(randomBytes(20));if(!u.totp_secret)await c.query('UPDATE users SET totp_secret=$1 WHERE id=$2',[encrypt(s),u.id]);return {secret:s,uri:`otpauth://totp/Nexo:${encodeURIComponent(u.email)}?secret=${s}&issuer=Nexo&digits=6&period=30`}})});
 for(const action of ['confirm','verify'])route('post','/auth/totp/'+action,async(req,res)=>{requireUser(req,null,true);const d=z.object({code:z.string().min(6).max(30)}).parse(req.body);return tx(async c=>{const u=(await c.query('SELECT * FROM users WHERE id=$1 FOR UPDATE',[req.user.id])).rows[0];if((action==='confirm'&&req.session.stage!=='TOTP_SETUP')||(action==='verify'&&req.session.stage!=='TOTP'))fail(403,'Sesión no válida para esta operación.');if(!u.totp_secret)fail(400,'Primero configurá el autenticador.');let counter=verifyTotp(decrypt(u.totp_secret),d.code,u.totp_last_counter);if(counter===null&&action==='verify'){const recovery=await c.query('UPDATE recovery_codes SET used_at=now() WHERE user_id=$1 AND code_hash=$2 AND used_at IS NULL RETURNING code_hash',[u.id,hash(d.code)]);if(!recovery.rowCount)fail(401,'Código incorrecto o ya utilizado.');counter=Number(u.totp_last_counter)}else if(counter===null)fail(401,'Código incorrecto o ya utilizado.');await c.query('UPDATE users SET totp_enabled=true,totp_last_counter=$1 WHERE id=$2',[counter,u.id]);let recoveryCodes;if(action==='confirm'){recoveryCodes=Array.from({length:10},()=>randomBytes(8).toString('hex'));for(const code of recoveryCodes)await c.query('INSERT INTO recovery_codes(user_id,code_hash) VALUES($1,$2)',[u.id,hash(code)])}await newSession(c,req,res,{...u,totp_enabled:true},'FULL');return {user:publicUser({...u,totp_enabled:true}),recoveryCodes}})});
}
