import {z} from 'zod';import sanitize from 'sanitize-html';import {q,tx,settings,outbox} from './db.mjs';import {requireUser} from './auth.mjs';import {fail,audit} from './security.mjs';
export const projectSchema=z.object({title:z.string().min(1).max(120),short:z.string().max(160).default(''),description:z.string().max(50000).default(''),category:z.string().max(100).default(''),subcategory:z.string().max(100).default('General'),status:z.enum(['Terminado','En desarrollo','Prototipo','Abandonado']).default('Terminado'),reference:z.string().max(5000).default(''),tool:z.string().max(100).default(''),formats:z.array(z.string().max(20)).max(40).default([]),version:z.string().min(1).max(30).default('1.0'),changelog:z.string().max(10000).default(''),requirements:z.string().max(5000).default(''),compatibility:z.string().max(5000).default(''),license:z.enum(['Uso personal','Uso comercial','Créditos obligatorios','Libre (CC0)','Personalizada']).default('Uso personal'),customLicense:z.string().max(10000).default(''),tags:z.array(z.string().max(40)).max(30).default([]),price:z.number().int().min(0).max(10000000).default(0),currency:z.literal('USD').default('USD'),demo:z.union([z.string().url().startsWith('https://'),z.literal('')]).default(''),repository:z.union([z.string().url().startsWith('https://'),z.literal('')]).default(''),installation:z.string().max(10000).default(''),videoUrl:z.union([z.string().url().startsWith('https://'),z.literal('')]).default('')});
const fields=['title','short','description','category','subcategory','development_status','reference','tool','formats','version','changelog','requirements','compatibility','license','custom_license','tags','price','currency','demo','repository','installation','video_url'];
const values=d=>[d.title,d.short,sanitize(d.description,{allowedTags:['p','br','h2','h3','strong','b','em','i','ul','ol','li','blockquote','code','pre','a'],allowedAttributes:{a:['href','title']},allowedSchemes:['https','mailto']}),d.category,d.subcategory,d.status,d.reference,d.tool,d.formats,d.version,d.changelog,d.requirements,d.compatibility,d.license,d.customLicense,d.tags,d.price,d.currency,d.demo,d.repository,d.installation,d.videoUrl];
export const projectSelect=`SELECT p.*,u.name seller,sp.verified,(SELECT a.id FROM assets a WHERE a.project_id=p.id AND a.purpose='image' AND a.status='CLEAN' ORDER BY a.sort_order,a.created_at LIMIT 1) image_id,(SELECT coalesce(avg(r.rating),0) FROM ratings r WHERE r.project_id=p.id) rating,(SELECT count(*) FROM ratings r WHERE r.project_id=p.id) reviews,(SELECT count(*) FROM orders o WHERE o.project_id=p.id AND o.status='PAID' AND o.gross>0) sales_count,(SELECT count(*) FROM download_events de WHERE de.project_id=p.id) downloads FROM projects p JOIN users u ON u.id=p.seller_id LEFT JOIN seller_profiles sp ON sp.user_id=p.seller_id`;
export const mapProject=p=>({id:p.id,title:p.title,short:p.short,description:p.description,category:p.category,subcategory:p.subcategory,status:p.development_status,tool:p.tool,formats:p.formats,version:p.version,changelog:p.changelog,requirements:p.requirements,compatibility:p.compatibility,license:p.license,tags:p.tags,price:Number(p.price),currency:p.currency,seller:p.seller,sellerId:p.seller_id,verified:p.verified,image:p.image_id?'/api/v1/media/'+p.image_id:'/images/code.svg',rating:Number(p.rating),reviews:Number(p.reviews),downloads:Number(p.downloads),sales:Number(p.sales_count),reference:p.reference,demo:p.demo,repository:p.repository,installation:p.installation,createdAt:p.created_at});
export async function publicConfig(){const s=await settings();return {preview:false,retentionDays:s.retentionDays,maxFileMB:s.maxFileMB,currencies:['USD'],commissions:{USD:{threshold:s.thresholdUsd,below:s.commissionBelowUsd,above:s.commissionAboveUsd},ARS:{threshold:s.thresholdArs,below:s.commissionBelowArs,above:s.commissionAboveArs}},minimumWithdrawals:{USD:s.minimumWithdrawalUsd,ARS:s.minimumWithdrawalArs},legalReady:s.legalReady}}
export function catalogRoutes(route){
 route('get','/config',publicConfig);
 route('get','/categories',async()=>({categories:(await q('SELECT * FROM categories WHERE active=true ORDER BY sort_order,name')).rows}));
 route('get','/projects',async req=>{const search=String(req.query.q||'').slice(0,120),limit=Math.min(Math.max(Number(req.query.limit)||100,1),100),offset=Math.max(Number(req.query.offset)||0,0);const {rows}=await q(projectSelect+" WHERE p.publication_status='PUBLISHED' AND u.status='ACTIVE' AND ($1='' OR to_tsvector('spanish',p.title||' '||p.short||' '||p.description) @@ plainto_tsquery('spanish',$1)) ORDER BY p.featured DESC,p.created_at DESC LIMIT $2 OFFSET $3",[search,limit,offset]);return {projects:rows.map(mapProject)}});
 route('get','/projects/:id',async req=>{const id=z.string().uuid().parse(req.params.id),p=(await q(projectSelect+" WHERE p.id=$1 AND p.publication_status='PUBLISHED' AND u.status='ACTIVE'",[id])).rows[0];if(!p)fail(404,'Proyecto no disponible.');const media=(await q("SELECT id,purpose,sort_order FROM assets WHERE project_id=$1 AND purpose IN('image','video') AND status='CLEAN' ORDER BY sort_order,created_at",[id])).rows;return {project:{...mapProject(p),media:media.map(a=>({...a,url:'/api/v1/media/'+a.id})),videoUrl:p.video_url}}});
 route('get','/sellers/:id',async req=>{const id=z.string().uuid().parse(req.params.id),s=(await q("SELECT u.id,u.name,sp.bio,sp.links,sp.verified FROM users u JOIN seller_profiles sp ON sp.user_id=u.id WHERE u.id=$1 AND u.status='ACTIVE'",[id])).rows[0];if(!s)fail(404,'Vendedor no disponible.');return {seller:s,projects:(await q(projectSelect+" WHERE p.seller_id=$1 AND p.publication_status='PUBLISHED'",[id])).rows.map(mapProject)}});
 route('post','/seller/register',async req=>{const u=requireUser(req);await tx(async c=>{await c.query('INSERT INTO seller_profiles(user_id) VALUES($1) ON CONFLICT DO NOTHING',[u.id]);if(u.role==='USER')await c.query("UPDATE users SET role='SELLER' WHERE id=$1",[u.id]);});return {ok:true}});
 route('patch','/seller/profile',async req=>{const u=requireUser(req,['SELLER','CREATOR']);const d=z.object({bio:z.string().max(3000),links:z.record(z.string().url().startsWith('https://')).default({})}).parse(req.body);await q('UPDATE seller_profiles SET bio=$1,links=$2 WHERE user_id=$3',[d.bio,d.links,u.id]);return {ok:true}});
 route('get','/seller/projects/:id',async req=>{const u=requireUser(req,['SELLER','CREATOR']);const p=(await q(projectSelect+' WHERE p.id=$1',[z.string().uuid().parse(req.params.id)])).rows[0];if(!p||p.seller_id!==u.id&&u.role!=='CREATOR')fail(403,'Proyecto ajeno.');return {project:{...mapProject(p),customLicense:p.custom_license,videoUrl:p.video_url},assets:(await q("SELECT id,purpose,status,original_name FROM assets WHERE project_id=$1 AND status NOT IN('REJECTED','DELETED')",[p.id])).rows}});
 route('get','/seller/projects',async req=>{const u=requireUser(req,['SELLER','CREATOR']);return {projects:(await q("SELECT id,title,publication_status,price,currency,created_at FROM projects WHERE seller_id=$1 ORDER BY created_at DESC",[u.id])).rows}});
 for(const method of ['post','patch'])route(method,method==='post'?'/seller/projects':'/seller/projects/:id',async req=>{const u=requireUser(req,['SELLER','CREATOR']),d=projectSchema.parse(req.body);if(d.videoUrl&&!['youtube.com','www.youtube.com','youtu.be','vimeo.com','www.vimeo.com'].includes(new URL(d.videoUrl).hostname))fail(400,'El video debe ser de YouTube o Vimeo.');return tx(async c=>{const id=method==='post'?null:z.string().uuid().parse(req.params.id);if(id){const p=(await c.query('SELECT * FROM projects WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!p||p.seller_id!==u.id&&u.role!=='CREATOR')fail(403,'No podés editar este proyecto.');if(['PUBLISHED','DELETING','DELETED'].includes(p.publication_status))fail(409,'Despublicá antes de editar. Un proyecto eliminado no se puede recuperar.');await c.query(`UPDATE projects SET ${fields.map((f,i)=>f+'=$'+(i+1)).join(',')},updated_at=now() WHERE id=$${fields.length+1}`,[...values(d),id]);if(u.role==='CREATOR')await audit(c,req,'EDIT_PROJECT',id);return {id}}const p=(await c.query(`INSERT INTO projects(seller_id,${fields.join(',')}) VALUES(${Array.from({length:fields.length+1},(_,i)=>'$'+(i+1)).join(',')}) RETURNING id`,[u.id,...values(d)])).rows[0];return p})});
 route('post','/seller/projects/:id/publish',async req=>{const u=requireUser(req,['SELLER','CREATOR']);return tx(async c=>{const p=(await c.query('SELECT * FROM projects WHERE id=$1 FOR UPDATE',[z.string().uuid().parse(req.params.id)])).rows[0];if(!p||p.seller_id!==u.id&&u.role!=='CREATOR')fail(403,'Proyecto ajeno.');if(['DELETING','DELETED'].includes(p.publication_status))fail(410,'Proyecto eliminado.');for(const f of ['title','short','description','reference','tool','requirements','compatibility','changelog','subcategory'])if(!p[f]?.trim())fail(400,'Completá todos los campos obligatorios.');if(!p.formats.length||!p.tags.length||p.license==='Personalizada'&&!p.custom_license)fail(400,'Completá formatos, tags y licencia.');const cat=(await c.query('SELECT 1 FROM categories parent JOIN categories child ON child.parent_id=parent.id WHERE parent.name=$1 AND child.name=$2 AND parent.active AND child.active',[p.category,p.subcategory])).rowCount;if(!cat)fail(400,'Categoría o subcategoría inválida.');const assets=(await c.query("SELECT purpose,status FROM assets WHERE project_id=$1 AND status NOT IN('DELETED','REJECTED')",[p.id])).rows;if(!assets.some(a=>a.purpose==='main'&&a.status==='CLEAN')||!assets.some(a=>a.purpose==='image'&&a.status==='CLEAN'))fail(409,'Esperá que los archivos y la portada completen el escaneo.');if(assets.filter(a=>a.purpose==='image').length>8||assets.filter(a=>a.purpose==='video').length+(p.video_url?1:0)>1)fail(400,'Demasiados archivos de referencia.');const s=await settings(c),status=s.requireApproval&&u.role!=='CREATOR'?'REVIEW':'PUBLISHED';await c.query('INSERT INTO project_versions(project_id,version,snapshot) VALUES($1,$2,$3)',[p.id,p.version,JSON.stringify(p)]);await c.query('UPDATE projects SET publication_status=$1,updated_at=now() WHERE id=$2',[status,p.id]);if(u.role==='CREATOR')await audit(c,req,'PUBLISH_PROJECT',p.id);return {status}})});
 route('post','/seller/projects/:id/unpublish',async req=>{const u=requireUser(req,['SELLER','CREATOR']);await tx(async c=>{const p=(await c.query('SELECT * FROM projects WHERE id=$1 FOR UPDATE',[z.string().uuid().parse(req.params.id)])).rows[0];if(!p||p.seller_id!==u.id&&u.role!=='CREATOR')fail(403,'Proyecto ajeno.');if(['DELETING','DELETED'].includes(p.publication_status))fail(410,'Proyecto eliminado.');await c.query("UPDATE projects SET publication_status='HIDDEN' WHERE id=$1",[p.id]);if(u.role==='CREATOR')await audit(c,req,'UNPUBLISH_PROJECT',p.id)});return {ok:true}});
 route('delete','/seller/projects/:id',async req=>{const u=requireUser(req,['SELLER','CREATOR']);z.literal('ELIMINAR').parse(req.body.confirmation);await tx(async c=>{const p=(await c.query('SELECT * FROM projects WHERE id=$1 FOR UPDATE',[z.string().uuid().parse(req.params.id)])).rows[0];if(!p||p.seller_id!==u.id&&u.role!=='CREATOR')fail(403,'Proyecto ajeno.');await c.query("UPDATE projects SET publication_status='DELETING',deleted_at=now() WHERE id=$1",[p.id]);await c.query('INSERT INTO deletion_tombstones(project_id) VALUES($1) ON CONFLICT DO NOTHING',[p.id]);await outbox(c,'purge:'+p.id,'purge',{projectId:p.id});if(u.role==='CREATOR')await audit(c,req,'DELETE_PROJECT',p.id)});return {status:'DELETING'}});
 route('get','/library',async req=>{const u=requireUser(req);return {items:(await q("SELECT e.*,coalesce(o.title_snapshot,p.title) title,p.publication_status IN('DELETING','DELETED') deleted FROM entitlements e JOIN projects p ON p.id=e.project_id LEFT JOIN orders o ON o.id=e.order_id WHERE e.user_id=$1 ORDER BY e.created_at DESC",[u.id])).rows}});
 route('get','/projects/:id/comments',async req=>({comments:(await q("SELECT c.*,u.name author FROM comments c JOIN users u ON u.id=c.author_id JOIN projects p ON p.id=c.project_id WHERE c.project_id=$1 AND c.hidden=false AND p.publication_status='PUBLISHED' ORDER BY c.highlighted DESC,c.created_at",[z.string().uuid().parse(req.params.id)])).rows}));
 route('post','/projects/:id/comments',async req=>{const u=requireUser(req);const d=z.object({body:z.string().trim().min(1).max(3000),parentId:z.string().uuid().nullable().optional()}).parse(req.body);const p=(await q("SELECT id FROM projects WHERE id=$1 AND publication_status='PUBLISHED'",[z.string().uuid().parse(req.params.id)])).rows[0];if(!p)fail(404,'Proyecto no disponible.');const r=await q('INSERT INTO comments(project_id,author_id,parent_id,body) VALUES($1,$2,$3,$4) RETURNING id',[p.id,u.id,d.parentId||null,d.body]);return r.rows[0]});
 route('put','/projects/:id/rating',async req=>{const u=requireUser(req),rating=z.number().int().min(1).max(5).parse(req.body.rating),id=z.string().uuid().parse(req.params.id);const allowed=(await q("SELECT 1 FROM entitlements e WHERE e.user_id=$1 AND e.project_id=$2 AND e.revoked_at IS NULL AND (e.origin='PURCHASE' OR EXISTS(SELECT 1 FROM download_events d WHERE d.user_id=$1 AND d.project_id=$2))",[u.id,id])).rowCount;if(!allowed)fail(403,'Necesitás comprar o descargar el proyecto para calificar.');await q('INSERT INTO ratings(user_id,project_id,rating) VALUES($1,$2,$3) ON CONFLICT(user_id,project_id) DO UPDATE SET rating=excluded.rating',[u.id,id,rating]);return {ok:true}});
 route('post','/comments/:id/highlight',async req=>{const u=requireUser(req,['SELLER','CREATOR']);const r=await q('UPDATE comments c SET highlighted=$1 FROM projects p WHERE c.id=$2 AND p.id=c.project_id AND p.seller_id=$3 RETURNING c.id',[z.boolean().parse(req.body.highlighted),z.string().uuid().parse(req.params.id),u.id]);if(!r.rowCount)fail(403,'Solo el vendedor puede destacar este comentario.');return {ok:true}});
 route('post','/reports',async req=>{const u=requireUser(req);const d=z.object({projectId:z.string().uuid().optional(),commentId:z.string().uuid().optional(),reason:z.string().trim().min(10).max(3000)}).refine(x=>!!x.projectId!==!!x.commentId).parse(req.body);await q('INSERT INTO reports(reporter_id,project_id,comment_id,reason) VALUES($1,$2,$3,$4)',[u.id,d.projectId||null,d.commentId||null,d.reason]);return {ok:true}});
 route('post','/copyright-claims',async req=>{const d=z.object({name:z.string().min(2).max(200),email:z.string().email(),projectUrl:z.string().url().max(1000),originalUrl:z.string().url().max(1000),description:z.string().min(30).max(10000),declaration:z.literal(true)}).parse(req.body);await q('INSERT INTO copyright_claims(name,email,project_url,original_url,description,declaration) VALUES($1,$2,$3,$4,$5,true)',[d.name,d.email,d.projectUrl,d.originalUrl,d.description]);return {ok:true}});
 route('post','/search-events',async req=>{const d=z.object({query:z.string().trim().min(1).max(120),results:z.number().int().nonnegative()}).parse(req.body);await q('INSERT INTO search_events(query,results) VALUES($1,$2)',[d.query,d.results]);return {ok:true}});
 route('post','/privacy-requests',async req=>{const u=requireUser(req),kind=z.enum(['ACCESS','CORRECT','DELETE']).parse(req.body.kind);await q('INSERT INTO privacy_requests(user_id,kind) VALUES($1,$2)',[u.id,kind]);return {ok:true}});
}
