import 'reflect-metadata';
import {NestFactory} from '@nestjs/core';import {Module,HttpException} from '@nestjs/common';import express from 'express';import helmet from 'helmet';import cookieParser from 'cookie-parser';import {ZodError} from 'zod';import {Redis} from 'ioredis';
import {loadSession,authRoutes} from './auth.mjs';import {catalogRoutes} from './catalog.mjs';import {paymentRoutes} from './paypal.mjs';import {storageRoutes} from './storage.mjs';import {walletRoutes} from './wallet.mjs';import {adminRoutes} from './admin.mjs';import {equal,fail,blind} from './security.mjs';import {q,settings,pool} from './db.mjs';
class AppModule{}Module({})(AppModule);
for(const name of ['DATABASE_URL','REDIS_URL','APP_ORIGIN','DATA_ENCRYPTION_KEY','DOWNLOAD_SIGNING_KEY'])if(!process.env[name])throw new Error(`${name} must be configured`);
const app=await NestFactory.create(AppModule,{bodyParser:false,logger:['error','warn','log']});const redis=new Redis(process.env.REDIS_URL,{maxRetriesPerRequest:2});
app.use(helmet({contentSecurityPolicy:false}));app.use(cookieParser());app.use(express.json({limit:'1mb'}));
app.use(async(req,res,next)=>{try{const path=req.path;const webhook=path==='/v1/payments/paypal/webhook';if(!webhook&&process.env.API_PROXY_SECRET&&!equal(req.headers['x-nexo-proxy']||'',process.env.API_PROXY_SECRET))fail(403,'Acceso directo no permitido.');if(!['GET','HEAD','OPTIONS'].includes(req.method)&&!webhook){if(req.headers['origin']!==process.env.APP_ORIGIN||req.headers['x-nexo-request']!=='1')fail(403,'Origen de solicitud inválido.');}await loadSession(req);const ip=req.clientIp||req.socket.remoteAddress;const blocked=await q("SELECT 1 FROM blocklist WHERE kind='IP' AND value_hash=$1",[blind(ip)]);if(blocked.rowCount)fail(403,'Acceso no disponible.');let max=300,window=60,key=path.split('/').slice(0,3).join('/');if(path.includes('/auth/')){max=12;window=900;}else if(path.includes('/uploads/'))max=240;else if(path.endsWith('/comments')){max=10;window=60;}else if(path==='/v1/withdrawals'){max=5;window=3600;}const rateKey='limit:'+key+':'+(req.user?.id||ip)+':'+Math.floor(Date.now()/1000/window);const count=await redis.eval("local n=redis.call('INCR',KEYS[1]); if n==1 then redis.call('EXPIRE',KEYS[1],ARGV[1]) end; return n",1,rateKey,window);if(count>max){res.setHeader('Retry-After',String(window));fail(429,'Demasiadas solicitudes. Esperá unos minutos.');}if(!webhook&&!path.includes('/auth/')&&path!=='/v1/config'&&!path.startsWith('/v1/admin/')&&req.user?.role!=='CREATOR'){const s=await settings();if(s.maintenance)fail(503,'Estamos realizando mantenimiento. Volvé en unos minutos.');}next()}catch(e){sendError(e,res)}});
function sendError(e,res){if(res.headersSent){res.destroy();return}if(e instanceof ZodError)return res.status(400).json({message:'Revisá los datos ingresados.',fields:e.issues.map(i=>({field:i.path.join('.'),message:i.message}))});if(e instanceof HttpException)return res.status(e.getStatus()).json(e.getResponse());if(e.code==='23505')return res.status(409).json({message:'La operación ya existe o fue procesada.'});console.error('Request failed',e.name,e.code||'',e.message?.slice(0,180));res.status(500).json({message:'No pudimos completar la operación. Intentá nuevamente.'})}
const http=app.getHttpAdapter().getInstance(),operations=[];
const route=(method,path,handler)=>{operations.push({method,path});http[method]('/v1'+path,async(req,res)=>{try{const result=await handler(req,res);if(result!==undefined&&!res.headersSent)res.json(result)}catch(e){sendError(e,res)}})};
authRoutes(route);catalogRoutes(route);paymentRoutes(route);storageRoutes(route);walletRoutes(route);adminRoutes(route);
route('get','/health',async()=>{await q('SELECT 1');return {status:'ok'}});
route('get','/openapi.json',async()=>({openapi:'3.1.0',info:{title:'Nexo Marketplace API',version:'0.1.0',description:'API REST. Autenticación de sesión HttpOnly. Operaciones mutantes requieren Origin y X-Nexo-Request: 1. Ver docs/API.md para campos y transiciones.'},servers:[{url:'/api/v1'}],paths:Object.fromEntries([...new Set(operations.map(o=>o.path))].map(path=>[path.replace(/:([a-zA-Z]+)/g,'{$1}'),Object.fromEntries(operations.filter(o=>o.path===path).map(o=>[o.method,{summary:o.method.toUpperCase()+' '+path,responses:{200:{description:'Operación completada'},400:{description:'Datos inválidos'},401:{description:'Sesión requerida'},403:{description:'Permiso denegado'},409:{description:'Conflicto de estado'},503:{description:'Servicio no configurado'}}}]))]))}));
http.use((err,req,res,next)=>sendError(err,res));
await app.listen(Number(process.env.PORT||4000),'0.0.0.0');
for(const sig of ['SIGINT','SIGTERM'])process.on(sig,async()=>{await app.close();await redis.quit();await pool.end();process.exit(0)});
