import {Worker,Queue} from 'bullmq';import {Redis} from 'ioredis';import nodemailer from 'nodemailer';import {pipeline} from 'node:stream/promises';import {createWriteStream,createReadStream} from 'node:fs';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {fileTypeFromFile} from 'file-type';import {createHash} from 'node:crypto';import {GetObjectCommand,DeleteObjectCommand} from '@aws-sdk/client-s3';import {q,tx,outbox,settings} from './db.mjs';import {s3,purgeProject,purgeAsset} from './storage.mjs';import {processPaypalEvent,paypal} from './paypal.mjs';import {releaseHolds} from './finance.mjs';import {backup} from './operations.mjs';
const exec=promisify(execFile),connection=new Redis(process.env.REDIS_URL,{maxRetriesPerRequest:null});const queue=new Queue('nexo-jobs',{connection});const mail=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:process.env.SMTP_SECURE==='true',auth:process.env.SMTP_USER?{user:process.env.SMTP_USER,pass:process.env.SMTP_PASSWORD}:undefined});
async function scan(id){const a=(await q('SELECT * FROM assets WHERE id=$1',[id])).rows[0];if(!a||!['QUARANTINE','SCANNING'].includes(a.status))return;if(a.project_id&&(await q("SELECT 1 FROM projects WHERE id=$1 AND publication_status IN('DELETING','DELETED')",[a.project_id])).rowCount)return;const dir=await fs.mkdtemp(path.join(os.tmpdir(),'nexo-scan-')),file=path.join(dir,'upload');try{await q("UPDATE assets SET status='SCANNING' WHERE id=$1",[id]);const obj=await s3.send(new GetObjectCommand({Bucket:a.bucket,Key:a.object_key}));await pipeline(obj.Body,createWriteStream(file));const stat=await fs.stat(file);if(stat.size!==Number(a.size))throw new Error('REJECT: size mismatch');const type=await fileTypeFromFile(file);const allowed=a.purpose==='main'?['zip','rar']:a.purpose==='video'?['mp4']:a.purpose==='receipt'?['png','jpg','webp','pdf']:['png','jpg','webp'];if(!type||!allowed.includes(type.ext))throw new Error('REJECT: file type not allowed');if(a.purpose==='main'){const listing=await exec('7z',['l','-slt',file],{timeout:60000,maxBuffer:8*1024*1024});if(/^Encrypted = \+/m.test(listing.stdout))throw new Error('REJECT: encrypted archives cannot be scanned');const expanded=[...listing.stdout.matchAll(/^Size = (\d+)$/gm)].reduce((s,m)=>s+Number(m[1]),0);if(expanded>2*1024**3||expanded>stat.size*100)throw new Error('REJECT: archive expansion limit');}
 await exec('clamscan',['--no-summary','--alert-encrypted=yes','--alert-exceeds-max=yes','--max-scansize=2048M','--max-filesize=500M','--max-recursion=20',file],{timeout:300000,maxBuffer:1024*1024});const h=createHash('sha256');for await(const b of createReadStream(file))h.update(b);await q("UPDATE assets SET status='CLEAN',real_type=$1,checksum=$2 WHERE id=$3 AND status='SCANNING'",[type.mime,h.digest('hex'),id]);}catch(e){if(e.message?.startsWith('REJECT:')||e.code===1){await q("UPDATE assets SET status='REJECTED',scan_reason=$1 WHERE id=$2",[e.message?.slice(0,200)||'Antivirus rejected file',id]);await s3.send(new DeleteObjectCommand({Bucket:a.bucket,Key:a.object_key}));}else{await q("UPDATE assets SET status='QUARANTINE',scan_reason='Escaneo pendiente; no disponible para descarga' WHERE id=$1",[id]);throw e}}finally{await fs.rm(dir,{recursive:true,force:true})}}
const worker=new Worker('nexo-jobs',async job=>{const record=(await q('SELECT * FROM outbox WHERE id=$1',[job.data.id])).rows[0];if(!record||record.processed_at)return;const d=record.payload;try{if(record.kind==='email'){const attachments=[];if(d.receiptId){const a=(await q("SELECT * FROM assets WHERE id=$1 AND purpose='receipt' AND status='CLEAN'",[d.receiptId])).rows[0];if(a){const obj=await s3.send(new GetObjectCommand({Bucket:a.bucket,Key:a.object_key}));attachments.push({filename:a.original_name,content:obj.Body})}}await mail.sendMail({from:process.env.EMAIL_FROM,to:d.to,subject:d.subject,text:d.text,attachments,messageId:`<${record.id}@nexo.local>`});}
 else if(record.kind==='backup')await backup();
 else if(record.kind==='scan')await scan(d.assetId);
 else if(record.kind==='purge_asset'){const a=(await q('SELECT * FROM assets WHERE id=$1',[d.assetId])).rows[0];if(a)await purgeAsset(a);}
 else if(record.kind==='purge')await purgeProject(d.projectId);
 else if(record.kind==='paypal_event')await processPaypalEvent(d.id);
 else if(record.kind==='refund'){const refund=await paypal('/v2/payments/captures/'+encodeURIComponent(d.captureId)+'/refund','POST',{amount:{value:(d.amount/100).toFixed(2),currency_code:'USD'},note_to_payer:d.reason.slice(0,255)},'refund-'+(d.requestId||d.orderId));if(d.requestId)await q("UPDATE refunds SET provider_id=$1,status='SUBMITTED' WHERE id=$2",[refund.id,d.requestId]);}
 else if(record.kind==='campaign'){const campaign=(await q('SELECT * FROM campaigns WHERE id=$1',[d.id])).rows[0];const users=(await q("SELECT u.id,u.email,cp.unsubscribe_token FROM users u JOIN communication_preferences cp ON cp.user_id=u.id WHERE cp.marketing=true AND u.status='ACTIVE' AND u.email_verified=true AND ($1='ALL' OR ($1='SELLERS' AND u.role='SELLER') OR ($1='BUYERS' AND EXISTS(SELECT 1 FROM orders o WHERE o.buyer_id=u.id AND o.status='PAID')))",[campaign.audience])).rows;for(const u of users)await tx(c=>outbox(c,'campaign:'+d.id+':'+u.id,'email',{to:u.email,subject:campaign.subject,text:campaign.body+'\n\nDejar de recibir promociones: '+process.env.APP_ORIGIN+'/preferencias?token='+u.unsubscribe_token}));await q("UPDATE campaigns SET status='SENT' WHERE id=$1",[d.id]);}
 await q('UPDATE outbox SET processed_at=now(),error=NULL WHERE id=$1',[record.id]);}catch(e){await q('UPDATE outbox SET attempts=attempts+1,error=$1 WHERE id=$2',[e.message?.slice(0,500),record.id]);throw e}},{connection,concurrency:3});
async function dispatch(){if(process.env.S3_BACKUP_BUCKET&&process.env.S3_BACKUP_CONTENT_BUCKET)await tx(c=>outbox(c,'backup:'+new Date().toISOString().slice(0,10),'backup',{}));const rows=(await q('SELECT id FROM outbox WHERE processed_at IS NULL AND available_at<=now() AND attempts<12 ORDER BY created_at LIMIT 100')).rows;for(const r of rows)await queue.add('outbox',{id:r.id},{jobId:r.id,attempts:12,backoff:{type:'exponential',delay:30000},removeOnComplete:true,removeOnFail:false});await releaseHolds()}
let running=false;const tick=async()=>{if(running)return;running=true;try{await dispatch()}catch(e){console.error('Worker dispatch failed:',e.message)}finally{running=false}};await tick();const interval=setInterval(tick,30000);worker.on('failed',(job,e)=>console.error('Job failed:',job?.id,e.message));
for(const sig of ['SIGINT','SIGTERM'])process.on(sig,async()=>{clearInterval(interval);await worker.close();await queue.close();await connection.quit();process.exit(0)});
