'use client';
import {useEffect,useState} from 'react';import {api} from '@/lib/api';import {toast} from 'sonner';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
export function AssetManager({projectId,onAssets}:{projectId:string;onAssets:(assets:any[])=>void}){
 const [items,setItems]=useState<any[]>([]),[selected,setSelected]=useState<any>(null);
 const refresh=()=>api('/seller/projects/'+projectId+'/assets').then(r=>{setItems(r.items);onAssets(r.items)}).catch(e=>toast.error(e.message));useEffect(()=>{if(projectId)refresh()},[projectId]);
 const move=async(a:any,delta:number)=>{const images=items.filter(x=>x.purpose==='image'&&x.status==='CLEAN');const i=images.findIndex(x=>x.id===a.id),j=i+delta;if(j<0||j>=images.length)return;[images[i],images[j]]=[images[j],images[i]];try{await api('/seller/projects/'+projectId+'/media-order','PATCH',{ids:images.map(x=>x.id)});refresh()}catch(e:any){toast.error(e.message)}};
 return <div className="stack"><div className="row"><h2>Archivos guardados</h2><button type="button" className="btn" onClick={refresh}>Actualizar estado</button></div>{items.map(a=><div key={a.id} className="panel"><div className="row"><span style={{overflowWrap:'anywhere'}}>{a.original_name}</span><span className="status-text">{({CLEAN:'Verificado',UPLOADING:'Subiendo',QUARANTINE:'En revisión',SCANNING:'Escaneando',DELETING:'Eliminando'} as any)[a.status]||a.status}</span></div><div className="toolbar" style={{marginTop:10}}>{a.purpose==='image'&&<><button type="button" className="btn" onClick={()=>move(a,-1)}>Mover antes</button><button type="button" className="btn" onClick={()=>move(a,1)}>Mover después</button></>}<button type="button" className="btn" onClick={()=>setSelected(a)}>Eliminar archivo</button></div></div>)}<p className="muted" style={{fontSize:12}}>La primera imagen es la portada. Para reemplazar un archivo, eliminá el anterior y subí el nuevo.</p><AlertDialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><AlertDialogContent><AlertDialogTitle>Eliminar este archivo</AlertDialogTitle><AlertDialogDescription>Se borrarán el archivo y sus copias de respaldo. Esta acción no se puede deshacer.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={async()=>{try{await api('/seller/assets/'+selected.id,'DELETE');setSelected(null);refresh()}catch(e:any){toast.error(e.message)}}}>Eliminar archivo</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>
}
