import {deletionNotice} from '@/lib/catalog';
export const administrativeClause='Acceso administrativo. El usuario reconoce y acepta que el equipo técnico y administrativo de la Plataforma puede acceder, revisar, conservar y descargar los archivos alojados, incluidos los correspondientes a proyectos de acceso pago, con fines de moderación de contenidos, verificación de integridad, resolución de disputas, prevención de fraude, respaldo técnico y cumplimiento de obligaciones legales o requerimientos de autoridad competente. Este acceso se limita a los fines indicados y no implica cesión de derechos de propiedad intelectual sobre la obra, que permanecen en cabeza del creador de la obra.';
const terms:[string,string][]=[
 ['1. Identificación y alcance','Nexo es una plataforma de publicación y adquisición de proyectos digitales. Antes de habilitar operaciones, su titular deberá completar en esta sección su nombre o razón social, CUIT, domicilio y email de contacto. Estos datos aún no están configurados; por ese motivo, esta versión no admite contrataciones. Los términos regulan el uso del sitio y se interpretan conforme a la legislación argentina, incluida la Ley 24.240 y el Código Civil y Comercial. Ninguna cláusula limita derechos irrenunciables.'],
 ['2. Registro y cuentas','Para descargar, comprar, comentar o publicar se requiere una cuenta con email verificado. El usuario debe proporcionar información veraz, ser mayor de edad y tener capacidad para contratar. Debe proteger su contraseña y notificar usos no autorizados. Las cuentas son personales. La plataforma puede suspender accesos ante fraude, infracciones o riesgos de seguridad, informando el motivo cuando ello no comprometa una investigación. El usuario podrá solicitar revisión por el canal de contacto.'],
 ['3. Publicaciones y responsabilidades','El vendedor declara contar con derechos suficientes para publicar y comercializar el contenido y responde por la veracidad de la descripción, compatibilidad, estado, archivos, licencia y referencias. Debe indicar limitaciones, dependencias y requisitos relevantes. No puede alojar malware, contenido ilegal, archivos de terceros sin permiso ni material que infrinja derechos. Los estados Prototipo, En desarrollo o Abandonado no eliminan la obligación de cumplir lo ofrecido. La plataforma puede revisar, despublicar o retirar contenidos reportados.'],
 ['4. Licencias y propiedad intelectual','La propiedad intelectual permanece en cabeza de su titular. La compra concede únicamente los usos descritos en la licencia presentada al contratar; no transfiere la autoría ni derechos no concedidos expresamente. Las licencias personales, comerciales, CC0 o personalizadas y las obligaciones de crédito deben interpretarse según su texto. El vendedor concede a la plataforma los permisos técnicos necesarios para alojar, presentar y entregar sus publicaciones conforme a estos términos. La plataforma no vende, cede, licencia ni redistribuye el contenido a terceros por cuenta propia.'],
 ['5. Acceso administrativo',administrativeClause],
 ['6. Compra, entrega y conservación local',deletionNotice+' El aviso se muestra antes de confirmar la adquisición y se registra su aceptación. La compra no incluye un servicio de almacenamiento permanente. La eliminación no borra las copias que el comprador ya haya guardado legítimamente en su equipo ni modifica la licencia adquirida. El historial de compra puede conservarse sin los archivos. Despublicar impide nuevas adquisiciones; eliminar revoca la descarga e inicia la purga de archivos y versiones almacenadas. La aceptación del aviso no exime de responsabilidad por incumplimiento ni impide reclamos legales.'],
 ['7. Precios, pagos y descuentos','Los proyectos pueden ser gratuitos o pagos. En la etapa inicial se cobra en USD mediante PayPal. El importe final y los descuentos se muestran antes de continuar al proveedor. Cualquier conversión o cargo del instrumento de pago debe consultarse al proveedor. El acceso se habilita después de verificar el pago por webhook. Una redirección del navegador no acredita por sí sola el pago. Las condiciones, licencia, precio y comisión aplicables se registran al crear la orden. Los cupones tienen alcance, vigencia y límites informados.'],
 ['8. Comisión y saldo del vendedor','La comisión vigente se muestra antes de publicar o cambiar el precio. Inicialmente es del 10% para operaciones inferiores a USD 100 y del 15% desde USD 100, con posibilidad de acuerdo individual. La configuración puede actualizarse para operaciones futuras. La comisión se calcula sobre el importe efectivamente cobrado después del descuento. Inicialmente la plataforma absorbe los gastos de PayPal. El saldo interno refleja obligaciones por ventas; no es una cuenta bancaria ni admite depósitos de uso general. Los saldos se registran separadamente por moneda.'],
 ['9. Retención, disputas y compensaciones','El neto de una venta queda pendiente durante el plazo informado, inicialmente siete días desde la captura confirmada. La fecha prevista de liberación se muestra en la billetera. Una disputa, contracargo, revisión de fraude o congelamiento fundado puede demorar la liberación. Los siete días no eliminan el riesgo de reclamos posteriores. Los reembolsos y contracargos se reflejan mediante ajustes contables trazables. Si los fondos ya fueron retirados, se registra una deuda y pueden suspenderse nuevos retiros hasta su compensación, sin impedir impugnar el ajuste.'],
 ['10. Verificación y cuentas de retiro','Antes del primer retiro se verifica la identidad mediante DNI frente y dorso, selfie y CUIL/CUIT, con revisión manual. Solo se admiten cuentas del mismo titular verificado; se prohíben retiros a terceros. La plataforma puede requerir evidencia de titularidad bancaria. Los cambios de cuenta exigen revisión del siguiente retiro. Se admiten únicamente monedas compatibles con la cuenta de destino. Los datos deben ser exactos y actualizados.'],
 ['11. Solicitudes de retiro','El vendedor solicita un monto no superior al saldo disponible y no inferior al mínimo vigente informado. Al confirmar, el importe queda reservado y no puede solicitarse nuevamente. Tu solicitud fue recibida. La transferencia puede demorar hasta 24 horas hábiles. El vencimiento se calcula según el calendario operativo publicado antes de habilitar retiros. Los estados son Pendiente, En proceso, Pagado y Rechazado. Si se rechaza, se informa el motivo y el importe vuelve al disponible, sin perjuicio de otros bloqueos vigentes. El pago se comunica por email con su comprobante. Ante demoras se informa el estado y un canal de consulta.'],
 ['12. Reembolsos y reclamos','El comprador puede reclamar por falta de entrega, archivos defectuosos, diferencias sustanciales con lo ofrecido, cargos no autorizados u otros supuestos legalmente aplicables. Se habilitará un canal visible de reclamos antes de operar. Los derechos de revocación y sus excepciones se aplican según la normativa vigente y el caso concreto; no se presume que descargar implique renunciar a ellos. El CREADOR analiza la solicitud y, cuando corresponde, tramita el reembolso por el proveedor. El reembolso completo revoca nuevas descargas de esa compra. Los parciales se tratan según su alcance. No se restringe el acceso a organismos de defensa del consumidor.'],
 ['13. Comunidad y moderación','Los comentarios deben ser pertinentes y respetuosos. Se prohíben spam, amenazas, suplantaciones y publicación de datos personales ajenos. Solo puede calificar quien compró o descargó válidamente el proyecto. El vendedor puede responder y destacar comentarios, pero no borrarlos. La plataforma recibe reportes y denuncias de derechos de autor y podrá ocultar contenidos durante su revisión, con registro de motivos.'],
 ['14. Disponibilidad, eliminación y cierre','El servicio puede interrumpirse por mantenimiento o incidentes. No se garantiza disponibilidad ininterrumpida, sin perjuicio de la responsabilidad legal aplicable. El vendedor puede despublicar o eliminar sus proyectos. La eliminación inicia la purga de originales, versiones, derivados y respaldos de contenido bajo control de la plataforma. Durante la purga se bloquean las nuevas descargas. Las copias ya entregadas a compradores no se pueden borrar remotamente. Los datos transaccionales se conservan por separado durante los plazos exigibles. Una obligación de conservación impuesta por autoridad competente prevalece sobre la eliminación ordinaria.'],
 ['15. Comunicaciones y cambios','Los avisos de seguridad, compra, retiro y moderación se envían al email registrado. Los emails promocionales dependen de las preferencias del usuario e incluyen una opción de baja. Los cambios materiales en estas condiciones se informarán y se registrará la versión aceptada cuando corresponda. No se aplicarán retroactivamente para alterar derechos ya adquiridos.'],
 ['16. Ley aplicable y controversias','Rige la legislación argentina. El usuario consumidor conserva los derechos y vías de reclamación que le correspondan, incluida la competencia judicial legalmente aplicable a su domicilio. Las partes procurarán resolver reclamos por el canal de atención antes de iniciar actuaciones, sin que ello constituya un requisito obligatorio ni limite plazos o recursos legales.']
];
const privacy:[string,string][]=[
 ['1. Responsable y marco normativo','Esta política describe el tratamiento de datos conforme a la Ley 25.326 y su normativa complementaria. Antes de habilitar registros, el titular de la plataforma deberá completar su identidad o razón social, CUIT, domicilio, contacto de privacidad e información del registro que corresponda ante la AAIP. La vista previa no recibe cuentas, documentos ni pagos.'],
 ['2. Datos que se tratan','Al operar se tratarán email, contraseña mediante hash, nombre y perfil; publicaciones, archivos y comentarios; compras, ventas y movimientos; datos de cuentas de retiro y CUIL/CUIT; documentos y selfie de verificación; sesiones, IP y registros de seguridad. No se almacenan números completos de tarjetas ni credenciales de PayPal del comprador. Las preferencias de tema se guardan localmente en el navegador.'],
 ['3. Finalidades','Los datos se usan para crear y proteger cuentas, publicar proyectos, procesar compras, habilitar descargas, verificar identidad y titularidad, tramitar retiros, prevenir fraude, moderar contenidos, atender reclamos y cumplir obligaciones legales. Las estadísticas se agregan cuando sea posible. El marketing se gestiona separadamente de las comunicaciones necesarias para el servicio.'],
 ['4. Información obligatoria y consentimiento','Se indica qué campos son necesarios para cada operación. Sin email verificado no pueden realizarse adquisiciones; sin identidad y cuenta verificadas no pueden solicitarse retiros. El usuario recibe información previa sobre la finalidad y los destinatarios del tratamiento y se registra el consentimiento cuando corresponda. La negativa a recibir publicidad no impide usar el servicio.'],
 ['5. Acceso y encargados','Acceden únicamente las personas y servicios que lo necesitan para los fines declarados: administración, alojamiento, almacenamiento, correo, procesamiento de pagos y soporte autorizado. Los documentos y datos bancarios no son públicos. Los perfiles, publicaciones y comentarios tienen visibilidad pública según su función. Los proveedores concretos, países y condiciones de tratamiento deben publicarse antes de operar. La plataforma no comercializa bases de datos personales.'],
 ['6. Transferencias internacionales','Si se utilizan proveedores fuera de Argentina, se verificará la adecuación del destino y se implementarán las garantías o excepciones legalmente aplicables. Se documentarán los países, encargados y mecanismos utilizados. No se considera suficiente una autorización genérica para sustituir las salvaguardas exigibles.'],
 ['7. Seguridad','Las contraseñas se guardan mediante hash resistente; los datos bancarios, factores de autenticación y documentos se cifran. Los archivos permanecen en almacenamiento privado. Las descargas requieren permisos y enlaces temporales. El CREADOR utiliza TOTP y recibe avisos por dispositivos nuevos. Se aplican controles de acceso, límites de solicitudes y auditoría. Los backups de datos están cifrados y se controla su restauración. Ningún sistema puede prometer ausencia absoluta de incidentes.'],
 ['8. Conservación y eliminación','Se conservan los datos solo durante el tiempo necesario para el servicio, reclamos y obligaciones aplicables. Los documentos de identidad tendrán un plazo de conservación definido antes de habilitar su carga. El contenido eliminado por el vendedor se purga de originales, versiones y respaldos bajo control de la plataforma. El historial transaccional puede permanecer por separado. Los backups de base de datos tienen retención limitada; al restaurarlos se reaplican las solicitudes de supresión. Una orden legal de conservación se gestiona con acceso restringido.'],
 ['9. Derechos del titular','El titular puede solicitar acceso, rectificación, actualización y supresión cuando corresponda, previa verificación de identidad proporcionada. El acceso se atiende dentro de diez días corridos y la rectificación o supresión dentro de cinco días hábiles en los términos legales. La supresión puede limitarse si existen obligaciones de conservación o derechos legítimos de terceros, explicando el motivo. El canal de privacidad debe configurarse y publicarse antes de operar. La AAIP es la autoridad de control competente para atender denuncias y reclamos relacionados con protección de datos.'],
 ['10. Cookies y almacenamiento local','Se emplean cookies necesarias para sesiones, seguridad y reconocimiento de dispositivos. La preferencia de tema puede guardarse en el dispositivo. No se instalan cookies publicitarias ni seguimiento de terceros en esta versión. Si se incorporan herramientas no esenciales, se informarán previamente y se ofrecerá el control que corresponda.'],
 ['11. Comunicaciones','Las comunicaciones transaccionales y de seguridad son necesarias para el servicio. La suscripción promocional es opcional y puede cancelarse sin afectar la cuenta. Los envíos segmentados deben respetar esa preferencia y no revelar destinatarios a otros usuarios.'],
 ['12. Menores y actualizaciones','El servicio está destinado a mayores de edad con capacidad para contratar. Ante datos de menores obtenidos indebidamente se evaluará su eliminación y las medidas correspondientes. Los cambios relevantes de esta política se comunicarán y quedará disponible su versión y fecha.']
];
export function Legal({privacy=false}:{privacy?:boolean}){return <article className="page legal"><div className="eyebrow">INFORMACIÓN LEGAL · VERSIÓN 21/09/2026</div><h1>{privacy?'Política de Privacidad':'Términos y Condiciones'}</h1><div className="notice">Borrador para revisión antes de operar. Falta completar los datos del responsable, proveedores y calendario de retiros. La vista previa no admite compras ni carga de datos personales.</div>{(privacy?privacySections:terms).map(([title,body])=><section key={title}><h2>{title}</h2><p>{body}</p></section>)}</article>}
const privacySections=privacy;
