export type Project = {id:string;title:string;short:string;description:string;category:string;subcategory:string;status:string;tool:string;formats:string[];version:string;changelog:string;requirements:string;compatibility:string;license:string;tags:string[];price:number;currency:string;seller:string;sellerId:string;verified:boolean;image:string;rating:number;reviews:number;downloads:number;reference:string;demo?:string;repository?:string;installation?:string;createdAt?:string;deleted?:boolean};
export const categories=['Todos','Diseño web / plantillas','Juegos 2D','Juegos 3D','Aplicaciones móviles','Aplicaciones de escritorio','Modelos 3D','Texturas y materiales','Sprites y pixel art','Audio y música','Scripts y herramientas','Otros'];
export const states=['Terminado','En desarrollo','Prototipo','Abandonado'];
export const licenses=['Uso personal','Uso comercial','Créditos obligatorios','Libre (CC0)','Personalizada'];
export const deletionNotice='Descargá y guardá una copia en tu equipo después de comprar. El vendedor puede eliminar este proyecto y sus archivos en cualquier momento. Si lo elimina, ya no podrás volver a descargarlos desde la plataforma. No conservamos copias del contenido eliminado. Esta condición no limita tus derechos legales como consumidor.';
const base={subcategory:'General',version:'1.0',changelog:'Primera versión del proyecto.',requirements:'Consultá la ficha y verificá la compatibilidad antes de comprar.',compatibility:'Windows, macOS y Linux',license:'Uso comercial',currency:'USD',sellerId:'demo-seller',verified:false,rating:0,reviews:0,downloads:0,reference:'Recurso de ejemplo para explorar la plataforma.'};
export const demoProjects:Project[]=[
 {...base,id:'islas-flotantes',title:'Skylands · Mundo low poly',short:'Un pequeño universo listo para tu próximo gran juego.',description:'Un entorno de islas flotantes con paisajes cálidos y una estética low poly.\n\nEste es un proyecto de muestra del catálogo. No hay archivos comerciales ni compras disponibles para este ejemplo.',category:'Modelos 3D',status:'Terminado',tool:'Blender',formats:['.blend','.fbx','.obj'],tags:['Low poly','Entornos','3D'],price:2900,seller:'Atlas Studio',image:'/images/island.png'},
 {...base,id:'bosque-pixel',title:'Forest Tales · Kit de aventura',short:'Dale vida a tu mundo con escenarios y sprites pixel art.',description:'Escenarios inspirados en los clásicos de aventura 2D, con una paleta cálida y detalles de bosque.\n\nProyecto de muestra. Las imágenes son ilustrativas y no se ofrece un archivo descargable.',category:'Sprites y pixel art',status:'Terminado',tool:'Godot',formats:['.png','.aseprite'],tags:['Pixel art','2D','Tileset'],price:1800,seller:'Pixel Norte',image:'/images/forest.png'},
 {...base,id:'materiales-estudio',title:'Forma · Materiales de estudio',short:'Texturas y materiales con una personalidad distinta.',description:'Una colección visual de vidrio, metal y cerámica para inspirar proyectos de diseño.\n\nProyecto de muestra del catálogo, sin archivos a la venta.',category:'Texturas y materiales',status:'Terminado',tool:'Blender',formats:['.blend','.png'],tags:['Materiales','PBR','Texturas'],price:2400,seller:'Forma Lab',image:'/images/materials.png'},
 {...base,id:'starter-react',title:'Orbit · Dashboard para React',short:'Un punto de partida limpio para construir tu aplicación.',description:'Un dashboard de ejemplo con diseño adaptable, tarjetas de métricas y navegación.\n\nProyecto ilustrativo del catálogo. No incluye descarga.',category:'Diseño web / plantillas',status:'En desarrollo',tool:'React',formats:['.tsx','.css'],tags:['React','Dashboard','UI'],price:0,seller:'Nico Dev',image:'/images/dashboard.svg'},
 {...base,id:'sonidos-arcade',title:'Arcade Sounds · Audio pack',short:'La próxima partida también tiene que sonar bien.',description:'Concepto de pack de sonidos para experiencias arcade.\n\nProyecto de muestra del catálogo. No contiene archivos de audio descargables.',category:'Audio y música',status:'Terminado',tool:'Ableton',formats:['.wav','.mp3'],tags:['SFX','Arcade','Audio'],price:1200,seller:'Onda Studio',image:'/images/audio.svg'},
 {...base,id:'script-herramientas',title:'Dev Essentials · Herramientas',short:'Pequeñas herramientas para grandes ideas.',description:'Concepto de utilidades de desarrollo y automatización.\n\nProyecto de muestra, sin descarga habilitada.',category:'Scripts y herramientas',status:'Prototipo',tool:'Python',formats:['.py','.md'],tags:['Python','Scripts','Herramientas'],price:0,seller:'Código Abierto',image:'/images/code.svg'},
];
export function priceLabel(p:Pick<Project,'price'|'currency'>){return p.price===0?'Gratis':new Intl.NumberFormat('es-AR',{style:'currency',currency:p.currency,maximumFractionDigits:2}).format(p.price/100)}
